from enum import Enum

class TipoUsuario(str, Enum):
    CLIENTE = "CLIENTE"
    FUNCIONARIO = "FUNCIONARIO"

class CargoFunc(str, Enum):
    ADMIN = "ADMIN"
    GERENTE = "GERENTE"
    ATENDENTE = "ATENDENTE"
    COZINHA = "COZINHA"

class CanalPedido(str, Enum):
    APP = "APP"
    TOTEM = "TOTEM"
    BALCAO = "BALCAO"
    PICKUP = "PICKUP"
    WEB = "WEB"

class StatusPedido(str, Enum):
    PENDENTE = "PENDENTE"
    EM_PREPARO = "EM_PREPARO"
    PRONTO = "PRONTO"
    ENTREGUE = "ENTREGUE"
    CANCELADO = "CANCELADO"

class FormaPagamento(str, Enum):
    CARTAO_CREDITO = "CARTAO_CREDITO"
    CARTAO_DEBITO = "CARTAO_DEBITO"
    PIX = "PIX"
    DINHEIRO = "DINHEIRO"

class StatusPagamento(str, Enum):
    APROVADO = "APROVADO"
    RECUSADO = "RECUSADO"
    ESTORNADO = "ESTORNADO"

class TipoMovEstoque(str, Enum):
    VENDA = "VENDA"
    CANCELAMENTO = "CANCELAMENTO"
    ENTRADA = "ENTRADA"
    SAIDA = "SAIDA"

class TipoMovPontos(str, Enum):
    GANHO = "GANHO"
    RESGATE = "RESGATE"
    ESTORNO = "ESTORNO"

class TipoDesconto(str, Enum):
    PERCENTUAL = "PERCENTUAL"
    VALOR_FIXO = "VALOR_FIXO"

class AcaoAuditoria(str, Enum):
    LOGIN_SUCESSO = "LOGIN_SUCESSO"
    LOGIN_FALHA = "LOGIN_FALHA"
    CRIACAO = "CRIACAO"
    ATUALIZACAO = "ATUALIZACAO"
    EXCLUSAO = "EXCLUSAO"
    ATUALIZACAO_STATUS = "ATUALIZACAO_STATUS"
    CANCELAMENTO = "CANCELAMENTO"
    MOVIMENTACAO_ESTOQUE = "MOVIMENTACAO_ESTOQUE"
    CONSENTIMENTO_ACEITO = "CONSENTIMENTO_ACEITO"
    CONSENTIMENTO_REVOGADO = "CONSENTIMENTO_REVOGADO"
