class ErrorCodes:
    # Autenticação
    CREDENCIAIS_INVALIDAS = "CREDENCIAIS_INVALIDAS"
    TOKEN_INVALIDO = "TOKEN_INVALIDO"
    REFRESH_TOKEN_INVALIDO = "REFRESH_TOKEN_INVALIDO"

    # Autorização
    FUNCIONARIO_REQUERIDO = "FUNCIONARIO_REQUERIDO"
    CARGO_NAO_PERMITIDO = "CARGO_NAO_PERMITIDO"
    ACESSO_NEGADO = "ACESSO_NEGADO"
    CLIENTE_OBRIGATORIO = "CLIENTE_OBRIGATORIO"
    APENAS_CLIENTE = "APENAS_CLIENTE"
    UNIDADE_NAO_PERMITIDA = "UNIDADE_NAO_PERMITIDA"

    # Entidades
    CLIENTE_NAO_ENCONTRADO = "CLIENTE_NAO_ENCONTRADO"
    FUNCIONARIO_NAO_ENCONTRADO = "FUNCIONARIO_NAO_ENCONTRADO"
    UNIDADE_NAO_ENCONTRADA = "UNIDADE_NAO_ENCONTRADA"
    PRODUTO_NAO_ENCONTRADO = "PRODUTO_NAO_ENCONTRADO"
    ITEM_CARDAPIO_NAO_ENCONTRADO = "ITEM_CARDAPIO_NAO_ENCONTRADO"
    PEDIDO_NAO_ENCONTRADO = "PEDIDO_NAO_ENCONTRADO"
    PROMOCAO_NAO_ENCONTRADA = "PROMOCAO_NAO_ENCONTRADA"

    # Cadastro
    EMAIL_JA_CADASTRADO = "EMAIL_JA_CADASTRADO"
    CPF_JA_CADASTRADO = "CPF_JA_CADASTRADO"
    ITEM_CARDAPIO_JA_CADASTRADO = "ITEM_CARDAPIO_JA_CADASTRADO"

    # Estoque
    ESTOQUE_INSUFICIENTE = "ESTOQUE_INSUFICIENTE"

    # Pedido
    ITEM_CARDAPIO_INDISPONIVEL = "ITEM_CARDAPIO_INDISPONIVEL"
    UNIDADE_OBRIGATORIA = "UNIDADE_OBRIGATORIA"
    PEDIDO_JA_FINALIZADO = "PEDIDO_JA_FINALIZADO"

    # Pagamento
    PEDIDO_CANCELADO = "PEDIDO_CANCELADO"
    PEDIDO_JA_PAGO = "PEDIDO_JA_PAGO"

    # Fidelização
    PONTOS_INVALIDOS = "PONTOS_INVALIDOS"
    SALDO_INSUFICIENTE = "SALDO_INSUFICIENTE"

    # Promoção
    DATA_INVALIDA = "DATA_INVALIDA"
    DESCONTO_INVALIDO = "DESCONTO_INVALIDO"
